version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Lint
          command: |
            . venv/bin/activate
            pylint src

  check_formatting:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout

      - run:
          name: Install requirements
          command: pip install --user black

      - run:
          name: Check Python Code Formatting
          command: python -m black --check --fast ./

workflows:
  version: 2
  build:
    jobs:
      - lint
      - check_formatting
